# Here we are going to install PHP extension requirements that did not come
# with the default PHP container. This will be necessary for Laravel and Swoole.
FROM php:8.1-cli
WORKDIR /srv/laravel

    RUN apk add --no-cache --virtual php_dependencies $PHPIZE_DEPS && \
        apk add --no-cache libstdc++ && \
        docker-php-ext-install bcmath ctype pdo_mysql pcntl && \
        pecl install swoole && \
        docker-php-ext-enable swoole && \
        apk del php_dependencies && \
        rm -rf /var/www && \
        chown -R www-data:www-data /srv/laravel

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
